### PR TITLE
fix: typo, decription to description

### PR DESCRIPTION
**Pull request by TomerFi**
Awesome action - Thanks!

I've started getting these in my workflows today for every run:

```shell
##[error]marvinpinto/action-automatic-releases/v1.0.0/action.yml (Line: 27, Col: 5): Unexpected value 'decription'
##[error]marvinpinto/action-automatic-releases/v1.0.0/action.yml (Line: 27, Col: 5): Unexpected value 'decription'
##[error]Fail to load marvinpinto/action-automatic-releases/v1.0.0/action.yml
```

I'm guessing GitHub started validating these action files today or something.

### CODE REVIEW

**Comment by plutov** [comment]
Same for me

**Comment by solomonope** [comment]
me too, How soon can this be merged?

**Comment by TomerFi** [comment]
Until this is merged, You can use the fixed branch from my repo.
replace:

```yaml
uses: marvinpinto/action-automatic-releases@v1.0.0
```

with:

```yaml
TomerFi/action-automatic-releases@fix-decription-typo
```

**Just please not, once this gets merged,
the fixed branch will probably get deleted.**

**Comment by TomerFi** [comment]
Looks like this PR is ignored and has been fixed in https://github.com/marvinpinto/action-automatic-releases/commit/8d9ddb2546e687f72855285d2719a11709cea6d0.

**Pull request closed without merging**
